### PR TITLE
Added optional parameter for SPI instance

### LINKED ISSUE #53: Allowing to pass a custom SPI object
Hi,

at the moment it is not possible to pass a custom SPI instance to the MCP2515 constructor.
I had this need in a project, so I have made the change on a local copy.
If you think this could be useful to others, I can provide a pull request.

Regards.

### PR DESCRIPTION
**Pull request by FStefanni**
Hi,

this pr adds an optional parameter to allow passing a custom SPI instance.
Implements the proposal of issue #53.
Closes #53.

Regards

### CODE REVIEW

**Comment by morcibacsi** [comment]
This is almost good, except that the spi.begin is called from inside the library. This way it can't be used with boards which allow you to use custom spi pins (for example ESP32, BluePill). As that requires you to call the spi.begin this way: spi.begin(SCK_PIN, MISO_PIN, MOSI_PIN, CS_PIN). I would refactor this in a way that the library gets a pointer to an already instantiated and correctly set up SPIClass.

**Comment by FStefanni** [comment]
Hi,

I agree, but doing this change is not the point of this pr.

Nevertheless, doing your proposed change is probably possible without breaking anything, by adding an additional boolean
parameter, to signal whether to perform the begin inside the library.
If this further improvement is of interest, I could check the code and in case improve the pr.

Regards.

**Comment by morcibacsi** [comment]
I see... my point was that IMO if we modify the constructors it is worth considering to inject the dependency as this way it adds more flexibility to the library.

**Comment by FStefanni** [comment]
Hi,

@morcibacsi I added the boolean, to support your case, with fully backward compatibility.
I hope this helps.

Regards.

**Comment by morcibacsi** [comment]
@FStefanni nice, thank you very much!

**Comment by FStefanni** [comment]
Hi,

the regression pipeline fails due to missing `#include <core_cm4.h>`.
Maybe something not properly configured? Seems not something up to this pr.

Regards.

**Comment by CarlosHdezM** [comment]
Hi @autowp, @FStefanni, and @morcibacsi. 
As I consider the possibility of using an SPI other than the default a huge step up, I decided to implement the functionality (#84) by continuing in the line of @FStefanni and taking the suggestions of @morcibacsi  for greater flexibility with boards that support assigning different pins to the SPI used.

I hope it can be considered to be merged.
Thank you!

**Comment by autowp** [comment]
Sounds good but there is some extra changes in library.properties to be removed from PR
Also "doBegin" sounds not clear

**Comment by CarlosHdezM** [comment]
> 

@autowp, I'm sorry for the confusion. I commented on this PR since I based the proposed changes on it. My proposed changes are actually in PR #84. I hope you can take a look at it. 
Thanks in advance!

**Comment by FStefanni** [comment]
Hi,

@CarlosHdezM thank you for the update, since my pr is very old: this has been a missing feature I needed in a (now) old project.

Regards.

**Pull request closed without merging**
